// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2175.Robot2014.subsystems;

import org.usfirst.frc2175.Robot2014.RobotMap;
import org.usfirst.frc2175.Robot2014.commands.*;
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Arm extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DoubleSolenoid armSolenoid = RobotMap.armArmSolenoid;
    SpeedController rollerBar = RobotMap.armRollerBar;
    DigitalInput armOutSwitch1 = RobotMap.armArmOutSwitch1;
    DigitalInput armOutSwitch2 = RobotMap.armArmOutSwitch2;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void MoveArmToPosition(boolean out) {
	if (out) {
            armSolenoid.set(DoubleSolenoid.Value.kForward);
	} else {
            armSolenoid.set(DoubleSolenoid.Value.kReverse);
	}
    }
    
    public void RunRollerBarAtSpeed(float speed) {
        rollerBar.set(speed);
    }
    
    public boolean IsArmOut() {
	//	return !(bool)armOutSwitch1->Get() || !(bool)armOutSwitch2->Get(); // The switches read 1 when the arm is NOT out. We need to typecast these values to bool and invert them before doing logic on them.
	if( armOutSwitch1.get() || armOutSwitch2.get() )
            return true;
	else
            return false;
    }
}

