// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2175.Robot2014.subsystems;

import org.usfirst.frc2175.Robot2014.RobotMap;
import org.usfirst.frc2175.Robot2014.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType; import edu.wpi.first.wpilibj.PIDSource.PIDSourceParameter;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Launcher extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DigitalInput latchSwitch = RobotMap.launcherLatchSwitch;
    DigitalInput winchUpSwitch = RobotMap.launcherWinchUpSwitch;
    SpeedController winchMotor = RobotMap.launcherWinchMotor;
    Encoder winchEncoder = RobotMap.launcherWinchEncoder;
    AnalogChannel ballSensor = RobotMap.launcherBallSensor;
    Solenoid latch = RobotMap.launcherLatch;
    DoubleSolenoid tension = RobotMap.launcherTension;
    Solenoid catcher = RobotMap.launcherCatcher;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
        
        latch.set(false); // Just to be safe
    }
    
    public boolean IsShooterArmDown() {
	return !latchSwitch.get();
    }
    public boolean IsWinchUp() {
        return !winchUpSwitch.get();
    }
    public boolean IsBall() {
        if (ballSensor.getAverageValue() > 100) { /* Whatever threshold indicates a ball */
            return true;
        } else {
            return false;
        }
    }
    public double GetBallSensorVoltage() {
        return ballSensor.getAverageVoltage();
    }
    public void RunWinchAtSpeed(double speed) {
            winchMotor.set(speed);
    }
    public void SetLatch(boolean release) {
            latch.set(release);
    }
    public void SetTension(boolean tensioned) {
        if (tensioned) {
            tension.set(DoubleSolenoid.Value.kForward);
        } else {
            tension.set(DoubleSolenoid.Value.kReverse);
        }
    }
}

