// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2175.Robot2014.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class Auton3DoubleBlindShot extends CommandGroup {
    
    public  Auton3DoubleBlindShot() {
        // add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
        
        addParallel(new ShiftToHighGear());
        addSequential(new MoveArmOut());
        
        addParallel(new ShiftToHighGear()); // YOU MUST REPLACE ALL INSTANCES OF ShiftToHighGear WITH TensionLauncher
        addSequential(new Shoot(false));
	
        addParallel(new ShiftToHighGear());
	addParallel(new RunRollerBar());
	addSequential(new UnwindWinch());
	
        addParallel(new ShiftToHighGear());
	addParallel(new RunRollerBar());
	addSequential(new Delay(2)); // To make sure the ball gets in
//	addSequential(new WaitForBall());
	
        addParallel(new ShiftToHighGear());
	addSequential(new ReleaseLatch());
	
        addParallel(new ShiftToHighGear());
	addParallel(new ArcadeDriveWithInputs(-0.75,0,2,true));
	addSequential(new WinchLauncherDown());
	
	addSequential(new UnwindWinch());
    }
}
