// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2175.Robot2014.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class Auton4LowGoal extends CommandGroup {
    
    public  Auton4LowGoal() {
        // add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
        
        /*
        
        addSequential(new DriveForDistance(15));
	
	addSequential(new RunRollerBarBackwards(),2);
                
        */
        
        // ----------------------------------
        // This auton routine does a long shot, then drives, gets the second ball, and does a short shot.
        // ----------------------------------
        
        addParallel(new ShiftToHighGear(),1.5); // This should stay tensioned
        addSequential(new MoveArmOut());
        
        addSequential(new Delay(0.75));
        
        addSequential(new Shoot(false));
        
        addParallel(new RunRollerBar(),0.5);
        addSequential(new ArcadeDriveWithInputs(0.75,0,0.5));
        
        addParallel(new MoveArmIn());
        addParallel(new UnwindWinch());
        addSequential(new ArcadeDriveWithInputs(-1,-0.15,2.0));
        
        addSequential(new ArcadeDriveWithInputs(-0.5,-0.1,0.5));
        
        addSequential(new MoveArmOut());
        
        addSequential(new Delay(0.75));
        
        addSequential(new Shoot());
    }
}
