// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2175.Robot2014.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc2175.Robot2014.Robot;

/**
 * This routine runs the automatic layup shot sequence, which slightly winds the winch then fires
 */
public class LayupShot extends CommandGroup {
    
    /**
     * Constructs this command to go through the full sequence.
     */
    public LayupShot() {
        this(true);
    }
    
    /**
     * Constructs this command to go through the sequence, with an option
     * to omit the final unwinding step.
     * @param unwind Whether to unwind the winch after the shot.
     */
    public LayupShot(boolean unwind) {
        
	addSequential(new WinchLauncherDown());
	addSequential(new UnwindWinch());
	addSequential(new LayupWinch(.45));
        addSequential(new ReleaseLatch());
        addSequential(new WinchLauncherDown());
        addSequential(new UnwindWinch());
    
        
        
    }
}
